# .github/workflows/docker.yml
name: Docker Build and Push

on:
  workflow_run:
    workflows: ["Terraform CI"]
    types:
      - completed

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.head_commit.message, '[docker]') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t my-ecr-app-repo .
          docker tag my-ecr-app-repo:latest ${{ secrets.REGISTRY }}/my-ecr-app-repo:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.REGISTRY }}/my-ecr-app-repo:latest
